<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" parallel="classes" name="Failed suite [Failed suite [Suite]]" guice-stage="DEVELOPMENT">
  <test thread-count="2" parallel="classes" name="Parallel Tests1(failed)(failed)">
    <classes>
      <class name="com.tutorialsninja.qa.testcases.LoginTest">
        <methods>
          <include name="verifyLoginWith_ValidEmailAnd_InvalidPassword1" invocation-numbers="4"/>
          <include name="setup"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- com.tutorialsninja.qa.testcases.LoginTest -->
      <class name="com.tutorialsninja.qa.testcases.RegisterTest">
        <methods>
          <include name="setup"/>
          <include name="tearDown"/>
          <include name="VerifyRegisteringAnAccount_Without_FillingAnyDetails"/>
        </methods>
      </class> <!-- com.tutorialsninja.qa.testcases.RegisterTest -->
    </classes>
  </test> <!-- Parallel Tests1(failed)(failed) -->
</suite> <!-- Failed suite [Failed suite [Suite]] -->
